spring:
  datasource:
    url: ${GOLF_DATASOURCE_LOCAL_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
          batch_size: 1000
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
  
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
    elasticsearch:
      client:
        reactive:
          endpoints: ${ELASTIC_SEARCH_URI}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: ${KAFKA_PRODUCER_KEY_SERIALIZER}
      value-serializer: ${KAFKA_PRODUCER_VALUE_SERIALIZER}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID}
      auto-offset-reset: ${KAFKA_CONSUMER_AUTO_OFFSET_RESET}
      key-deserializer: ${KAFKA_CONSUMER_KEY_DESERIALIZER}
      value-deserializer: ${KAFKA_CONSUMER_VALUE_DESERIALIZER}

logging:
  file:
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.example.screen_golf: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
  api-docs:
    path: /v3/api-docs
    enabled: true
  packages-to-scan: com.example.screen_golf
  paths-to-match: /api/**

jwt:
  secret: ${GOLF_JWT_SECRET}
  expiration: ${GOLF_JWT_EXPIRATION}
  refresh-expiration: ${GOLF_JWT_REFRESH_EXPIRATION}

kakao:
  pay:
    admin-key: ${KAKAOPAY_ADMIN_KEY}
    secret-key: ${KAKAOPAY_SECRET_KEY}

discord:
  webhook-uri: ${DISCORD_WEBHOOK_URI}

server:
  port: 8080

