spring:
  datasource:
    url: ${GOLF_DATASOURCE_LOCAL_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

logging:
  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 30
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  discord:
    webhook-uri: ${DISCORD_WEBHOOK_URI}

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match: /api/**
  swagger-ui:
    path: /api-test
    display-request-duration: true
    groups-order: DESC
    operations-sorter: method
    disable-swagger-default-url: false
    urls:
      - url: http://localhost:8080/v3/api-docs
        name: ScreenGolf API Docs
  api-docs:
    groups:
      enabled: true

jwt:
  secret: ${GOLF_JWT_SECRET}
  expiration: ${GOLF_JWT_EXPIRATION}

kakaopay:
  client-id: ${KAKAOPAY_CLIENT_ID}
  client-secret: ${KAKAOPAY_CLIENT_SECRET}
  secret-key: ${KAKAOPAY_SECRET_KEY}

